### ISSUE TITLE
Catwalk is not working in Firefox and Edge

### ISSUE THREAD

**Issue by sublibra** [qlik-oss/catwalk#102]
In Firefox we receive a Security error 

In Edge the app list is shown but it is not possible to open an app

**Comment by sublibra** [comment]
Few people are using Edge at least based on 30 last day's on qlikcore related pages
```
Webbläsare	Sessioner
Chrome	2 100
Safari	364
Firefox	211
Mozilla Compatible Agent	170
Internet Explorer	112
Edge	93
```

**Comment by hrigner** [comment]
Firefox is working, Edge is still troublesome. Add some info about this for Edge-users.
