### ISSUE TITLE
Run Locally(Not working) - What does it mean? 

### ISSUE THREAD

**Issue by FemilAntony** [qlik-oss/catwalk#196]
Hi,

This is a good tool to gain insight about data model. I tried the Qlik Hosted Catwalk UI with Qlik Sense desktop of a sample app. 

I tried run locally option by executing npm install and start in command prompt of windows by pointing the directory to where catwalk is downloaded but didn't work. Can you provide details steps of how to execute run UI Locally? 

Can you also explain does the data gets exposed?

**Comment by peol** [comment]
Hi!

Glad you like the tool :)

1) What errors do you get? `npm start` should prompt a URL that you can open in your browser (something like `Server running at http://localhost:1234`). Make sure you have an engine running locally (either Qlik Sense, or Qlik Core on port `9076`).

2) The data in your app is only exposed locally, between your computer and the engine you connect to. No data is passed through catwalk. We will be clarifying this when solving #186.

**Comment by FemilAntony** [comment]
Hi, Thanks for the response!!!

At this point of time i am not taking any risk to test this tool on server/enterprise.

Currently i opened an app in  Qlik Sense desktop in my PC and launched Qlik Hosted catwalk UI.

What i am trying to achieve is open an app in Qlik Sense desktop in my pc and try to run catwalk UI locally. 

I see you mentioned 2 commands for ex npm install and npm start so my question is where to execute these commands?  should i execute this in command prompt of my PC or on server where Qlik Sense enterprise is installed?

It would be great if you provide the screenshot of how to enable run UI locally option.

![catwalk screenshot](https://user-images.githubusercontent.com/29525897/53827570-6fa8b280-3f49-11e9-81f6-3920bde16ced.PNG)

**Comment by peol** [comment]
Hi, there are instructions in the README.md file but they were pretty sparse so I've updated them now: https://github.com/qlik-oss/catwalk#local

In your case, you're missing the Node.js dependency mentioned on the above link. Let me know if that solves your issue.

**Comment by peol** [comment]
Hi @FemilAntony — any updates?

**Comment by sublibra** [comment]
No feedback, closing issue. Please open again if the error still occurs.
