### ISSUE TITLE
No posibility to select in fields with "always one selected value" option

### ISSUE THREAD

**Issue by dimitree2k** [qlik-oss/catwalk#203]
I can't change any value in such fields.
![image](https://user-images.githubusercontent.com/45994551/54361915-51893380-4668-11e9-8984-fd2fdf6a2069.png)

**Comment by peol** [comment]
Related: https://core.qlik.com/services/qix-engine/apis/qix/definitions/#nxdimensioninfo `qIsOneAndOnlyOne` property would be `true` when the field is in this state.
