### ISSUE TITLE
Allow export from the hypercube (enhancement)

### ISSUE THREAD

**Issue by shaun-hope** [qlik-oss/catwalk#222]
Would be nice to be able to download the Hybercube (CSV only) once created

**Comment by hrigner** [comment]
Yes, I totally agree!

**Comment by hrigner** [comment]
So, what exactly do you mean with the Hypercube to CSV, do you want to export the resulting data you see in the hypercube?

**Comment by peol** [comment]
I believe he's referring to https://core.qlik.com/services/qix-engine/apis/qix/genericobject/#exportdata which will give a URL to a downloadable file for the hypercube data. Whether that links works for all products from catwalk needs to be tested (Qlik Core, Qlik Sense Desktop, Qlik Sense Enterprise, Qlik Cloud) I guess :)
