### ISSUE TITLE
Show loosely coupled tables with red/dashed lines

### ISSUE THREAD

**Issue by shaun-hope** [qlik-oss/catwalk#235]
The Data Model Viewer shows loosely coupled tables with a dashed red line between the join dimension that was loosened.

Simiarly, if a circular reference is created and the Qlik Engine loosens the connection between two tables, the Data Model Viewer shows this with the same red dashed line.

For me (using QSE) this is the *only* case that I go back to the Data Model Viewer for since Catwalk doesn't display the loose join, it seems like this would be helpful for Qlik Core users to see where the connection has been loosened...

**Comment by hrigner** [comment]
Hi @shaun-hope !

I implemented this here -> deploy-preview-239--catwalk-qlikcore.netlify.com .
Do you think it fulfils your need?

**Comment by shaun-hope** [comment]
Hi @hrigner , sorry for the delayed response - this looks really great!

Thank you!
Shaun
