### ISSUE TITLE
measures dont load

### ISSUE THREAD

**Issue by cookiejest** [qlik-oss/catwalk#307]
hey we added some master measures to a qlik core app using enigma but they do not appear in the catwalk UI.

Any ideas?

**Comment by axelssonHakan** [comment]
To be able to show the correct type we require that the `qType` is set to measure
https://github.com/qlik-oss/corectl/blob/master/test/projects/using-entities/measures.json#L5

Using **corectl** will force you to do this >>
`Error: validation error in file /Users/han/myMeasure.json: measures must have qType: measure`

**Comment by cookiejest** [comment]
is it case sensitive? I created the 'measure' like this and it wasn't displaying it :o.

      const newMeasure = await newApp.createMeasure({
        "qInfo": {
          "qId": "Measure01",
          "qType": "Measure"
        },
        "qMeasure": {
          "qLabel": "testmeasure1",
          "qDef": "=sum(1)"
        },
        "qMetaDef": {
          "title": "Some Title",
          tags: []
        }
      });

**Comment by axelssonHakan** [comment]
yes 😬
But shouldn't be
We will fix that in both catwalk and corectl!

Thanks

**Comment by hrigner** [comment]
catwalk is fetching the measure list with `qMeasureListDef` having `qType: 'measure`. Since it is possible to create a measure with basically any `qType`, it gets impossible for us to list any measure that don't have `qType: 'measure'`. Closing this issue for now!
