### ISSUE TITLE
Sort order for first table

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/catwalk#43]
Today we sort based on number of fields.
A better metric to determine first table is perhaps number of keys in the table as that would most likely be the fact table

**Comment by gabbaxx** [comment]
The first table is currently the one with the most rows. Would key count really be better?

**Comment by mindspank** [comment]
I guess it depends, but in a traditional star schema (and probably also in a snowflake) the fact table should be the table with most keys going into it is probably the table that you are most concerned about as that is most likely the target for your data transformations.

**Comment by hrigner** [comment]
This have been prototyped, and the result is really messy with no obvious improvements compared to the sort order we have today.
