### ISSUE TITLE
Data island

### ISSUE THREAD

**Issue by aalteirac** [qlik-oss/catwalk#45]
Using an app with data islands shows only one of them:
DMV shows: 
![image](https://user-images.githubusercontent.com/8478296/47219723-efc1e780-d3af-11e8-9f26-46163333d78a.png)
kitty says:
![image](https://user-images.githubusercontent.com/8478296/47219753-0700d500-d3b0-11e8-8231-ae9e12cde8cf.png)

**Comment by hrigner** [comment]
Fixed with #57
