### ISSUE TITLE
Selection tooltip: Some funky text parsing

### ISSUE THREAD

**Issue by mindspank** [qlik-oss/catwalk#68]
See attached screenshot. When hovering over a selection in the selection bar you get . .
Guessing there is some blank string value that has a appended dot to it.
Faulty text: "total of 910 values. ."

![image](https://user-images.githubusercontent.com/1181922/47660709-e565d180-db97-11e8-94af-e7f2e69b415a.png)

**Comment by axelssonHakan** [comment]
We have a task to redesign the tooltip to not use the default **title** attribute since it´s not possible to style using css. We will use some other attribute to make the tooltips more readable.
