### ISSUE TITLE
Sort order for key fields

### ISSUE THREAD

**Issue by cerjoh** [qlik-oss/catwalk#70]
In key fields, possible values are not sorted first. Non-key fields have the right sorting.

Recreate issue using demo app BranchCore.qvf:
Select value "Qlik" in _company_. The field _fullname_ now shows possible values on top (as expected). However, key field _entityId_ is not sorted with possible values on top.

Thanks for a great tool!

**Comment by hrigner** [comment]
Fixed with #72
